# -*- coding: utf-8 -*-
"""Linear.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/113YKJupxshP-_AuuiOu6GyANbOKiA-pU
"""

#import some necessary variables
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pickle

#loading the data set
data=pd.read_csv('Real_estate.csv')

#having some flavour of the data
data.head()

"""Here the data set is composed of age of the house,the distance to the nearest station, number of convenient stores, longitude,latitude and the estimated price per unit area"""

#some exploratory data analysis
data.describe()

"""The range of values will be used as input for our streamlit app. Remember i'm not going deep into the analysis my idea is just to create a simple linear regression model to be used and deploy in streamlit."""

X=data.drop(columns=['Y house price of unit area','No'])
y=data['Y house price of unit area']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model=LinearRegression()
model.fit(x_train,y_train)

#predicting some values
y_pred=model.predict(x_test)

input=[[2012.12,12.3,45,287,58,20]]

model = pickle.load(open('model.pkl','rb'))

model.predict(input)

#now we save the weight of our linear model
#pickle.dump(model,open('model.pkl','wb'))



"""Now the second phase is the web app using streamlit"""

#!pip install streamlit

!pip install pyngrok



!ngrok authtoken 1lSl5RMkADZ2p4HYnMk3ZQcqzNw_5KvvAFxRwEPJz9UcboW7R

!nohup streamlit run app.py &

from pyngrok import ngrok 
url = ngrok.connect(port = 8501)
url

!streamlit run --server.port 80 app.py >/dev/null

